# @package task
project: sirius
name: SiriusATEC

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  # name: sirius_diff
  name: aliengo
terrain: easy
# terrain: sirius_atec

# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling: {.*_joint: 0.5}
  max_delay: 1
  alpha: [0.6, 0.9]

command:
  class: Command2
  linvel_x_range: [-1.0, 1.2]
  linvel_y_range: [-0.8, 0.8]
  angvel_range: [-2.0, 2.0]
  yaw_stiffness_range: [0.5, 1.0]
  use_stiffness_ratio: 0.9
  stand_prob: 0.05

observation:
  command:
    command:
  policy:
    root_linvel_b:    {yaw_only: true}
    root_angvel_b:
    projected_gravity_b: {noise_std: 0.05}
    joint_pos_multistep: {steps: 4, noise_std: 0.05}
    joint_vel_multistep: {steps: 4, noise_std: 0.2}
    prev_actions: {steps: 3}

reward:
  loco:
    linvel_exp:         {weight: 1.5, yaw_only: true}
    angvel_z_exp:       {weight: 1.2}
    angvel_xy_l2:       {weight: 0.02}
    linvel_z_l2:        {weight: 0.5}
    base_height_l1:     {weight: 2.0, target_height: 0.4}
    root_upright:       {weight: 1.0}
    survival:           {weight: 1.0}
  reg:
    energy_l1:          {weight: 2.0e-4}
    joint_vel_l2:       {weight: 0.001}
    joint_acc_l2:       {weight: 1.0e-7}
    joint_torques_l2:   {weight: 5.0e-6}
    action_rate_l2:     {weight: 0.01}
    action_rate2_l2:    {weight: 0.005}
    feet_air_time:      {weight: 0.1, body_names: .*_foot, thres: 0.4}
  debug:
    _enabled_: false
    linvel_projection:  {weight: 0.5}
    feet_sliding:       {weight: 1.0, body_names: .*foot}
    feet_contact_count: {weight: 1.0, body_names: .*foot}

termination:
  crash_body(crash): {body_names_expr: ["base", ".*hip"], t_thres: 0.02}
  fall_over: {xy_thres: 0.9}

randomization:
  perturb_body_mass:
    (?!(front|back)).*: [0.95, 1.1]
  perturb_body_materials:
    body_names: ".*_foot"
    static_friction_range:  [0.5, 4.0]
    dynamic_friction_range: [0.5, 4.0]
    restitution_range:      [0.0, 0.5]
    homogeneous: true # ${task.homogeneous}
  motor_params:
    actuator_name: base_legs
    stiffness_range:  
      F[L,R]_hip_joint:   [0.9, 1.1]
      F[L,R]_thigh_joint: [0.9, 1.1]
      F[L,R]_calf_joint:  [0.9, 1.1]
      R[L,R]_hip_joint:   [0.9, 1.1]
      R[L,R]_thigh_joint: [0.9, 1.1]
      R[L,R]_calf_joint:  [0.9, 1.1]
    damping_range:
      F[L,R]_hip_joint:   [0.9, 1.1]
      F[L,R]_thigh_joint: [0.9, 1.1]
      F[L,R]_calf_joint:  [0.9, 1.1]
      R[L,R]_hip_joint:   [0.9, 1.1]
      R[L,R]_thigh_joint: [0.9, 1.1]
      R[L,R]_calf_joint:  [0.9, 1.1]
    scale_factor_range:
      .*_hip_joint:   [0.9, 1.1]
      .*_thigh_joint: [0.9, 1.1]
      .*_calf_joint:  [0.9, 1.1]
  reset_joint_states_scale:
    pos_scales:
      .*: [0.8, 1.2]
  # random_impulse: {}
  # drive_model_properties:
  #   joint_names: .*_(HFE|KFE)
  #   velocity_resistance_range: [0.0, 10.0]