# @package task
project: sirius
name: SiriusDemo

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: sirius_wheel
terrain: sirius_demo

# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

action:
  _target_: active_adaptation.envs.mdp.action.LegWheel
  leg_scaling: {.*_(HAA|HFE|KFE): 1.0}
  wheel_scaling: {.*_WHEEL: 10.0}

command:
  class: SiriusDemoCommand
  homogeneous: false # if `true`, all envs share the same initial state and command
  teleop: false
  transition_prob:
    - [1.0, 0.0]
    - [1.0, 0.0]

observation:
  command_mode_: # won't be normalized
    command_mode:
  command:
    command:
  policy:
    # root_angvel_b:
    projected_gravity_b: {noise_std: 0.05}
    joint_pos_multistep: {steps: 6, interval: 2, noise_std: 0.05, joint_names: .*_(HAA|HFE|KFE)}
    # joint_vel_multistep: {steps: 4, noise_std: 0.2, joint_names: .*}
    prev_actions: {steps: 2}
    # sirius_joint_deviation: {}
  priv:
    applied_action:
    applied_torque:
    root_angvel_b:
    root_linvel_b:    {yaw_only: true}
    external_forces:  {body_names: ["trunk"]}
    body_height:      {body_names: [.*hip, .*_FOOT]}
    contact_indicator:  {body_names: [".*_FOOT"], timing: false}
  terrain:
    height_scan: {x_range: [-1.2, 1.2], y_range: [-1.0, 1.0], x_resolution: 0.2, y_resolution: 0.2}

reward:
  loco:
    sirius_lin_vel_xy:    {weight: 1.5}
    sirius_lin_vel_z:     {weight: 1.5}
    sirius_ang_vel_z:     {weight: 1.0}
    sirius_pitch:         {weight: 1.0}
    sirius_yaw:           {weight: 1.0}
    sirius_base_height:   {weight: 1.0}

    sirius_jump_turning:  {weight: 10.0}
    sirius_jump_behave:   {weight: 2.0}
    sirius_land_behave:   {weight: 0.5}
    sirius_walk_behave:   {weight: 0.4}
    angvel_xy_l2:         {weight: 0.01}
    _eval_: "lambda a,b,c,d,e,f,g,h,i,j,k: (a+b+c+d+e+f)*f+g+h+i+j+k"
  joint_reg:
    _compile_: true
    energy_l1:          {weight: 0.0001}
    joint_acc_l2:       {weight: 2.5e-7, joint_names: .*_(HAA|HFE|KFE)}
    joint_deviation_l2: {weight: 0.1, joint_names: .*HAA}
    joint_vel_l2:       {weight: 0.002, joint_names: .*_(HAA|HFE|KFE)}
    joint_vel_limits:   {weight: 0.4, joint_names: .*_(HAA|HFE|KFE), factor: 0.4}
    # joint_tau_limits:   {weight: 0.4, joint_names: .*_(HAA|HFE|KFE), factor: 0.8}
    action_rate_l2:     {weight: 0.01}
    action_rate2_l2:    {weight: 0.002}
    survival:           {weight: 1.0}
  contact_reg:
    lateral_swing_height: {weight: 2.0, feet_names: .*_FOOT}
    undesired_contact:  {body_names: ["trunk", ".*(hip|thigh|calf)"], weight: 0.25}
    wheel_contact_direction: {weight: 0.5}
    feet_air_time:      {weight: 0.4, body_names: .*_FOOT, thres: 0.4}
    max_feet_height:    {weight: 2.0, body_names: .*_FOOT, target_height: 0.2}
    feet_sliding:       {weight: 0.5, body_names: .*_FOOT}
  # safety:
  #   joint_torque_limits: {weight: 0.2, enabled: true, joint_names: .*_(HFE|KFE), factor: 0.8}
  #   joint_vel_limits:    {weight: 0.1, enabled: true, joint_names: .*_(HFE|KFE), factor: 0.5}
  debug:
    _enabled_: false
    joint_torques_l2:   {weight: 1.0e-4, enabled: false}
    feet_contact_count: {weight: 1.0, enabled: false, body_names: .*_FOOT}

termination:
  crash_leg(crash): {body_names_expr: [".*thigh"], t_thres: 0.02}
  crash_body(crash): {body_names_expr: ["trunk", ".*hip"], t_thres: 0.02}
  sirius_jump: {height_thres: 0.25}

randomization:
  perturb_body_mass:
    (?!(front|back)).*: [0.95, 1.1]
  perturb_body_materials:
    body_names: ".*_FOOT"
    static_friction_range:  [0.5, 2.0]
    dynamic_friction_range: [0.5, 2.0]
    restitution_range:      [0.0, 0.5]
    homogeneous: true # ${task.homogeneous}
  motor_params:
    actuator_name: base_legs
    stiffness_range:  
      .*_HAA: [0.8, 1.2]
      .*_HFE: [0.8, 1.2]
      .*_KFE: [0.8, 1.2]
    damping_range:
      .*_HAA: [0.8, 1.2]
      .*_HFE: [0.8, 1.2]
      .*_KFE: [0.8, 1.2]
      .*_WHEEL: [0.8, 1.2]
    scale_factor_range:
      .*_HAA: [0.9, 1.1]
      .*_HFE: [0.9, 1.1]
      .*_KFE: [0.9, 1.1]
    armature_range:
      .*: [0.0, 0.02]
  reset_joint_states_scale:
    pos_scales:
      .*: [0.8, 1.2]
  random_impulse: {prob: 0.0025}
  # drive_model_properties:
  #   joint_names: .*_(HFE|KFE)
  #   velocity_resistance_range: [0.0, 10.0]